### ISSUE TITLE
Getting a KeyError on data

### ISSUE THREAD

**Issue by MicDeDuiwel** [mlschmitt/twitter-likes-exporter#2]
Firstly, thanks for writing this script!

Has something changed since you made this script? I'm getting the following error:

> $ python3 download_tweets.py
> Starting retrieval of likes for Twitter user ■■■■■■...
> Traceback (most recent call last):
>   File "/home/■■■/Repositories/twitter-likes-exporter/download_tweets.py", line 117, in <module>
>     downloader.retrieve_all_likes()
>   File "/home/■■■/Repositories/twitter-likes-exporter/download_tweets.py", line 21, in retrieve_all_likes
>     likes_page = self.retrieve_likes_page()
>   File "/home/■■■/Repositories/twitter-likes-exporter/download_tweets.py", line 49, in retrieve_likes_page
>     return self.extract_likes_entries(response.json())
>   File "/home/■■■/Repositories/twitter-likes-exporter/download_tweets.py", line 52, in extract_likes_entries
>     return raw_data['data']['user']['result']['timeline_v2']['timeline']['instructions'][0]['entries']
> KeyError: 'data'

I have also tried to unprivate my twitter account to see if that works, but it does not.

**Comment by MicDeDuiwel** [comment]
Nevermind! I realised I was using my twitter handle instead of using the numeric userID.
