### ISSUE TITLE
KeyError on 'result'

### ISSUE THREAD

**Issue by manofgloss** [mlschmitt/twitter-likes-exporter#3]
Heya, wondering if Twitter/X has cut this off from working.

Run the script (on two different linux boxes) and both fail at the same result. This differs from #2 as I am using the correct numeric userID:

> $ python3 download_tweets.py
> Starting retrieval of likes for Twitter user <numeric userID>...
> Fetching likes page: 1...
> ...
> Fetching likes page: 35...
> Traceback (most recent call last):
>   File "/home/ollie/twitter-likes-exporter-main/download_tweets.py", line 117, in <module>
>     downloader.retrieve_all_likes()
>   File "/home/ollie/twitter-likes-exporter-main/download_tweets.py", line 30, in retrieve_all_likes
>     tweet_parser = TweetParser(raw_tweet)
>   File "/home/ollie/twitter-likes-exporter-main/tweet_parser.py", line 11, in `__init__`
>     self.key_data = raw_tweet_json["content"]["itemContent"]["tweet_results"]["result"]
> KeyError: 'result'

This is using fresh cookie/auth data for both. Any pointers? Thanks in advance

**Comment by psellwood** [comment]
Installed and used this today for the first time - worked without issue so the problem you are facing is unlikely to be Twitter/X blocking this solution.

Sorry I don't have an answer however.

**Comment by eevmanu** [comment]
@manofgloss I had the same problem and I fixed it by adding some validations in

https://github.com/mlschmitt/twitter-likes-exporter/blob/b2173de9c75a094a63cd4984bd7bb455364755b8/tweet_parser.py#L1-L13

here are the validations

```py
        if "content" not in raw_tweet_json:
            print(f'raw_tweet_json=')
            self.is_valid_tweet = False
            return

        if "itemContent" not in raw_tweet_json["content"]:
            print(f'raw_tweet_json["content"]=')
            self.is_valid_tweet = False
            return

        if "tweet_results" not in raw_tweet_json["content"]["itemContent"]:
            print(f'raw_tweet_json["content"]["itemContent"]=')
            self.is_valid_tweet = False
            return

        if "result" not in raw_tweet_json["content"]["itemContent"]["tweet_results"]:
            print(f'raw_tweet_json["content"]["itemContent"]["tweet_results"]=')
            self.is_valid_tweet = False
            return
```

in my case the error was in page 118, you would see something like this

```sh
Fetching likes page: 118...
raw_tweet_json["content"]["itemContent"]["tweet_results"]=
raw_tweet_json["content"]=
raw_tweet_json["content"]=
```

~ 21.3K liked tweets (~11 MB) in ~8m 🎉👏

p.s.: thx @mlschmitt for the project 👍

p.s. 2: I suggest handle errors here https://github.com/mlschmitt/twitter-likes-exporter/blob/b2173de9c75a094a63cd4984bd7bb455364755b8/download_tweets.py#L26-L35 and write to the file because you could lose all progress if there is an error in the middle, and the only solution is to retry it (maybe this could flag our twitter account with suspicious behavior ... who knows 🤷‍♂️)

**Comment by manofgloss** [comment]
@eevmanu thanks for the pointers, python really isn't my forté. After sticking all of those validations into the tweet parser it did actually seem to complete, throwing up a few error tweets in the console:
`Fetching likes page: 42...`
`raw_tweet_json["content"]["itemContent"]["tweet_results"]=`
`Fetching likes page: 43...`
`Fetching likes page: 52...`
`raw_tweet_json["content"]["itemContent"]["tweet_results"]=`
`Fetching likes page: 53...`
`Fetching likes page: 60...`
`raw_tweet_json["content"]["itemContent"]["tweet_results"]=`
`Fetching likes page: 61...`
`Done. Likes JSON saved to: ./liked_tweets.json`

So, three problem tweets all with the same issue - maybe deleted? But it seems to really ruin the json formatting and then the `parse_tweets_json_to_html.py` script fails due to the formatting

> root@JUP-MINT-01:/home/ollie/twitter-likes-exporter-main# python3 parse_tweets_json_to_html.py
> Saving tweets to /home/ollie/twitter-likes-exporter-main/tweet_likes_html/index.html...
> Downloading image https://pbs.twimg.com/profile_images/1328248846896431105/cS58u9OC_normal.jpg...
> Traceback (most recent call last):
>   File "/home/ollie/twitter-likes-exporter-main/parse_tweets_json_to_html.py", line 120, in <module>
>     parser.write_tweets_to_html()
>   File "/home/ollie/twitter-likes-exporter-main/parse_tweets_json_to_html.py", line 24, in write_tweets_to_html
>     tweet_html = self.create_tweet_html(tweet_data)
>   File "/home/ollie/twitter-likes-exporter-main/parse_tweets_json_to_html.py", line 34, in create_tweet_html
>     self.save_remote_image(tweet_data["user_avatar_url"], full_path)
>   File "/home/ollie/twitter-likes-exporter-main/parse_tweets_json_to_html.py", line 91, in save_remote_image
>     with open(local_path, 'wb') as handler:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/ollie/twitter-likes-exporter-main/tweet_likes_html/images/avatars/1328085608703483905.jpg'

Even when attempting to tidy up the JSON manually it's still unhappy

**Comment by eevmanu** [comment]
hey @manofgloss 👋,

> So, three problem tweets all with the same issue - maybe deleted?

yep, maybe but I think value from `raw_tweet_json["content"]["itemContent"]["tweet_results"]` is a list of tweets not a single tweet unit ... but I'm not 100% sure, need to debug that probably

> But it seems to really ruin the json formatting and then the parse_tweets_json_to_html.py script fails due to the formatting

from the error stack trace you shared I think the problem is that there was an attempt to download the avatar picture locally in a path that already exist, verified it here https://github.com/mlschmitt/twitter-likes-exporter/blob/b2173de9c75a094a63cd4984bd7bb455364755b8/parse_tweets_json_to_html.py#L87-L88, but looks like the file was not found, because probably I mistake when downloading it https://github.com/mlschmitt/twitter-likes-exporter/blob/b2173de9c75a094a63cd4984bd7bb455364755b8/parse_tweets_json_to_html.py#L90

being honest I'm trying to guess since I didn't test `parse_tweets_json_to_html.py`, for me getting the json file was a enough success 💪🏽

**Comment by jonasfrede** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/ollie/twitter-likes-exporter-main/tweet_likes_html/images/avatars/1328085608703483905.jpg'

Hi @manofgloss,

I just ran this script and had the same problem. If you haven't fixed this on your end, my solution was as follows: The line 
https://github.com/mlschmitt/twitter-likes-exporter/blob/b2173de9c75a094a63cd4984bd7bb455364755b8/parse_tweets_json_to_html.py#L91
expects that the respective subfolders already exist in the filesystem. Therefore, the script worked after adding the subfolders "images\avatars", "images\tweets" and "tweets" to the main output folder "tweet_likes_html".

**Comment by ewoks** [comment]
@eevmanu great tips!!!
I made a small PR with proposed improvements..

cc: @mlschmitt
