### ISSUE TITLE
error in download_tweets.py

### ISSUE THREAD

**Issue by Schnirivadze** [mlschmitt/twitter-likes-exporter#7]
Error:
```
Starting retrieval of likes for Twitter user 1371351228509196295...
Fetching likes page: 1...
Fetching likes page: 2...
Traceback (most recent call last):
  File "./twitter-likes-exporter-main/download_tweets.py", line 117, in <module>
    downloader.retrieve_all_likes()
  File "./twitter-likes-exporter-main/download_tweets.py", line 30, in retrieve_all_likes
    tweet_parser = TweetParser(raw_tweet)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "./twitter-likes-exporter-main/tweet_parser.py", line 11, in __init__
    self.key_data = raw_tweet_json["content"]["itemContent"]["tweet_results"]["result"]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'

```

`config.json` is filled with needed data

**Comment by jonasfrede** [comment]
This is the same error as discussed in #3, a possible fix and additional validations are described there. Maybe these will be merged into the main repository soon.
